GET http://localhost:5159/api/games

###
GET http://localhost:5159/api/games/game01

###
POST http://localhost:5159/api/games
Content-Type: application/json

{
  "name": "AAA",
  "genre": "Action-Adventure",
  "price": 110.99,
  "releaseDate": "1986-02-21"
}

###
PUT http://localhost:5159/api/games/game03
Content-Type: application/json

{
  "name": "The Legend of Myth"
}

###
DELETE http://localhost:5159/api/games/game02
