GET http://localhost:5159/api/games

###
GET http://localhost:5159/api/games/id01

###
POST http://localhost:5159/api/games
Content-Type: application/json

{
  "name": "AAA",
  "genre": "id02",
  "price": 87.99,
  "releaseDate": "1986-02-21"
}

###
PUT http://localhost:5159/api/games/23fcff0d-83d0-4782-84a2-a0f3288e12e4
Content-Type: application/json

{
  "name": "The Legend of Myth"
}

###
DELETE http://localhost:5159/api/games/id03
